
class InverseAttrDectector:

	def __init__(self):
		pass


	def IsInverseAttr(self, attrName):
		attrList = self._getInverseAttrList()
		if attrName in attrList:
		    retVal = True
		else:
			retVal = False
		return retVal



	def _getInverseAttrList(self):
		return {
			"IsActingUpon": "",
			"HasExternalReference": "",
			"OfPerson": "",
			"OfOrganization": "",
			"ToCant": "",
			"ToAlignmentCurve": "",
			"ToHorizontal": "",
			"ToVertical": "",
			"ContainedInStructure": "",
			"HasExternalReferences": "",
			"ToLinearAxis": "",
			"PositioningElement": "",
			"ClassificationForObjects": "",
			"HasReferences": "",
			"ClassificationRefForObjects": "",
			"UsingCurves": "",
			"PropertiesForConstraint": "",
			"IsDefinedBy": "",
			"Declares": "",
			"Controls": "",
			"HasCoordinateOperation": "",
			"CoversSpaces": "",
			"CoversElements": "",
			"AssignedToFlowElement": "",
			"HasPorts": "",
			"HasControlElements": "",
			"DocumentInfoForObjects": "",
			"HasDocumentReferences": "",
			"IsPointedTo": "",
			"IsPointer": "",
			"DocumentRefForObjects": "",
			"FillsVoids": "",
			"ConnectedTo": "",
			"IsInterferedByElements": "",
			"InterferesElements": "",
			"HasProjections": "",
			"HasOpenings": "",
			"IsConnectionRealization": "",
			"ProvidesBoundaries": "",
			"ConnectedFrom": "",
			"HasCoverings": "",
			"ExternalReferenceForResources": "",
			"BoundedBy": "",
			"HasTextureMaps": "",
			"ProjectsElements": "",
			"VoidsElements": "",
			"HasSubContexts": "",
			"PartOfW": "",
			"PartOfV": "",
			"PartOfU": "",
			"IsGroupedBy": "",
			"ToFaceSet": "",
			"LibraryInfoForObjects": "",
			"HasLibraryReferences": "",
			"LibraryRefForObjects": "",
			"HasRepresentation": "",
			"IsRelatedWith": "",
			"RelatesTo": "",
			"ToMaterialConstituentSet": "",
			"AssociatedTo": "",
			"HasProperties": "",
			"ToMaterialLayerSet": "",
			"ToMaterialProfileSet": "",
			"IsDeclaredBy": "",
			"IsTypedBy": "",
			"HasAssignments": "",
			"Nests": "",
			"IsNestedBy": "",
			"HasContext": "",
			"IsDecomposedBy": "",
			"Decomposes": "",
			"HasAssociations": "",
			"PlacesObject": "",
			"HasFillings": "",
			"IsRelatedBy": "",
			"Relates": "",
			"Engages": "",
			"EngagedIn": "",
			"PartOfComplex": "",
			"ContainedIn": "",
			"Positions": "",
			"IsPredecessorTo": "",
			"IsSuccessorFrom": "",
			"OperatesOn": "",
			"ReferencedBy": "",
			"PositionedRelativeTo": "",
			"ReferencedInStructures": "",
			"ShapeOfProduct": "",
			"HasShapeAspects": "",
			"PartOfPset": "",
			"PropertyForDependance": "",
			"PropertyDependsOn": "",
			"HasApprovals": "",
			"HasConstraints": "",
			"DefinesType": "",
			"DefinesOccurrence": "",
			"Defines": "",
			"PartOfComplexTemplate": "",
			"PartOfPsetTemplate": "",
			"InnerBoundaries": "",
			"Corresponds": "",
			"RepresentationMap": "",
			"LayerAssignments": "",
			"OfProductRepresentation": "",
			"RepresentationsInContext": "",
			"LayerAssignment": "",
			"StyledByItem": "",
			"MapUsage": "",
			"ResourceOf": "",
			"OfShapeAspect": "",
			"ContainsElements": "",
			"ServicedBySystems": "",
			"ReferencesElements": "",
			"AssignedToStructuralItem": "",
			"ConnectsStructuralMembers": "",
			"AssignedStructuralActivity": "",
			"SourceOfResultGroup": "",
			"LoadGroupFor": "",
			"ConnectedBy": "",
			"ResultGroupFor": "",
			"IsMappedBy": "",
			"UsedInStyles": "",
			"ServicesBuildings": "",
			"ServicesFacilities": "",
			"HasColours": "",
			"HasTextures": ""
        }.keys()